<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Caching\Caching.csproj" />
    <ProjectReference Include="..\Order.Application\Order.Application.csproj" />
    <ProjectReference Include="..\Order.Domain\Order.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Helpers\SeedData\contract.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\organizationTypeData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\organizationData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\subscriptionData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
