// <auto-generated />
using System;
using Classroom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Classroom.Infrastructure.Migrations
{
    [DbContext(typeof(ClassroomDbContext))]
    [Migration("20251025170541_UpdateCurriculumEnrollmentV2Tbl")]
    partial class UpdateCurriculumEnrollmentV2Tbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Classroom.Domain.Entities.Annoucement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasComment("Foreign key to classroom");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasComment("Announcement content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Announcement creation timestamp");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("Optional file attachment URL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasComment("Announcement title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Announcement last update timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId")
                        .HasDatabaseName("IX_Announcements_ClassroomId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Announcements_CreatedAt");

                    b.HasIndex("ClassroomId", "CreatedAt")
                        .HasDatabaseName("IX_Announcements_ClassroomCreatedAt");

                    b.ToTable("Announcement", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.AnswerAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionAttemptId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionAttemptId")
                        .HasDatabaseName("IX_AnswerAttempt_QuestionAttempt");

                    b.HasIndex("QuestionAttemptId", "AnswerId")
                        .IsUnique()
                        .HasDatabaseName("IX_AnswerAttempt_QuestionAttempt_Answer");

                    b.ToTable("AnswerAttempt", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificateUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CourseEnrollmentId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurriculumEnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseEnrollmentId")
                        .IsUnique();

                    b.HasIndex("CurriculumEnrollmentId")
                        .IsUnique();

                    b.HasIndex("VerificationCode")
                        .IsUnique();

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasComment("Unique classroom code for joining");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("URL to classroom cover image");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Record creation timestamp");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("Classroom description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasComment("Classroom end date");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Grade level (e.g., Grade 1, Grade 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasComment("Classroom display name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasComment("Classroom start date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("Classroom status (Active, Inactive, Archived)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to teacher (Identity service)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasComment("Record last update timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Classrooms_ClassCode_Unique");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Classrooms_Status");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("IX_Classrooms_TeacherId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Classrooms_DateRange");

                    b.ToTable("Classroom", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.ClassroomStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Identifier for the student");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("ClassroomStudent", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.CourseEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer")
                        .HasComment("Foreign key to course");

                    b.Property<int?>("CurriculumEnrollmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Percentage of course completed (0-100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("Enrollment status (InProgress, Compeleted)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasComment("Foreign key to student (Identity service)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_Enrollments_CourseId");

                    b.HasIndex("CurriculumEnrollmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Enrollments_Status");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Enrollments_StudentId");

                    b.ToTable("CourseEnrollments", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.CurriculumEnrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Percentage of curriculum completed (0-100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "CurriculumId");

                    b.ToTable("CurriculumEnrollments", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("StudentQuizId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentQuizId")
                        .HasDatabaseName("IX_QuizAttempt_StudentQuiz");

                    b.HasIndex("StudentQuizId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_QuizAttempt_StudentQuiz_AttemptNumber");

                    b.ToTable("QuizAttempt", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizQuestionAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("QuizAttemptId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Score")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuizAttemptId")
                        .HasDatabaseName("IX_QuizQuestionAttempt_QuizAttempt");

                    b.HasIndex("QuizAttemptId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("IX_QuizQuestionAttempt_QuizAttempt_Question");

                    b.ToTable("QuizQuestionAttempt", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentLessonProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp when student completed the lesson");

                    b.Property<int>("EnrollmentId")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer")
                        .HasComment("Reference to Lesson (from resource-service)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Progress status: InProgress, Completed, Failed.");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StudentLessonProgress_Status");

                    b.ToTable("StudentLessonProgress", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentQuiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("MaxAttemptAllowed")
                        .HasColumnType("integer");

                    b.Property<int>("QuizId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StudentSectionProgressId")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentSectionProgressId")
                        .IsUnique();

                    b.HasIndex("QuizId", "StudentSectionProgressId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentQuiz_Quiz_SectionProgress");

                    b.ToTable("StudentQuiz", (string)null);
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentSectionProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Timestamp when the section was completed");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasComment("FK to Section (from resource-service)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("Progress status: NotStarted, InProgress, Completed, Submitted, Failed.");

                    b.Property<int>("StudentLessonProgressId")
                        .HasColumnType("integer")
                        .HasComment("FK to StudentLessonProgress");

                    b.HasKey("Id");

                    b.HasIndex("SectionId")
                        .HasDatabaseName("IX_StudentSectionProgress_SectionId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_StudentSectionProgress_Status");

                    b.HasIndex("StudentLessonProgressId")
                        .HasDatabaseName("IX_StudentSectionProgress_LessonProgressId");

                    b.HasIndex("StudentLessonProgressId", "SectionId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentSectionProgress_LessonSection_Unique");

                    b.ToTable("StudentSectionProgress", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.Annoucement", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.Classroom", "Classroom")
                        .WithMany("Annoucements")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Announcements_Classroom");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.AnswerAttempt", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.QuizQuestionAttempt", "QuestionAttempt")
                        .WithMany("AnswerAttempts")
                        .HasForeignKey("QuestionAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionAttempt");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.CourseEnrollment", "CourseEnrollment")
                        .WithOne("Certificate")
                        .HasForeignKey("Classroom.Domain.Entities.Certificate", "CourseEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Classroom.Domain.Entities.CurriculumEnrollment", "CurriculumEnrollment")
                        .WithOne("Certificate")
                        .HasForeignKey("Classroom.Domain.Entities.Certificate", "CurriculumEnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CourseEnrollment");

                    b.Navigation("CurriculumEnrollment");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.ClassroomStudent", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.Classroom", "Classroom")
                        .WithMany("ClassroomStudents")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClassroomStudents_Classroom");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.CourseEnrollment", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.CurriculumEnrollment", "CurriculumEnrollment")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CurriculumEnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CurriculumEnrollment");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizAttempt", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.StudentQuiz", "StudentQuiz")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("StudentQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentQuiz");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizQuestionAttempt", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.QuizAttempt", "QuizAttempt")
                        .WithMany("QuestionAttempts")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizAttempt");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentLessonProgress", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.CourseEnrollment", "Enrollment")
                        .WithMany("LessonProgress")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentQuiz", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.StudentSectionProgress", null)
                        .WithOne("StudentQuiz")
                        .HasForeignKey("Classroom.Domain.Entities.StudentQuiz", "StudentSectionProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentSectionProgress", b =>
                {
                    b.HasOne("Classroom.Domain.Entities.StudentLessonProgress", "LessonProgress")
                        .WithMany("SectionProgress")
                        .HasForeignKey("StudentLessonProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonProgress");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.Classroom", b =>
                {
                    b.Navigation("Annoucements");

                    b.Navigation("ClassroomStudents");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.CourseEnrollment", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("LessonProgress");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.CurriculumEnrollment", b =>
                {
                    b.Navigation("Certificate");

                    b.Navigation("CourseEnrollments");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizAttempt", b =>
                {
                    b.Navigation("QuestionAttempts");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.QuizQuestionAttempt", b =>
                {
                    b.Navigation("AnswerAttempts");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentLessonProgress", b =>
                {
                    b.Navigation("SectionProgress");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentQuiz", b =>
                {
                    b.Navigation("QuizAttempts");
                });

            modelBuilder.Entity("Classroom.Domain.Entities.StudentSectionProgress", b =>
                {
                    b.Navigation("StudentQuiz");
                });
#pragma warning restore 612, 618
        }
    }
}
