<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Product.Application\Product.Application.csproj" />
    <ProjectReference Include="..\Product.Domain\Product.Domain.csproj" />
	<ProjectReference Include="..\..\..\BuildingBlocks\Caching\Caching.csproj" />

  </ItemGroup>

  <ItemGroup>
    <None Update="Helpers\SeedData\componentData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\kitComponentData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\kitData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\kitImageData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Helpers\SeedData\planData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>