<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="UnitOfWork\**" />
    <Compile Remove="Events\**" />
    <Compile Remove="ValueObjects\**" />
    <Compile Remove="Entities\UserTests.cs" />
    <Compile Remove="Entities\TeacherProfileTests.cs" />
    <Compile Remove="Entities\UserInvariantsTests.cs" />
    <EmbeddedResource Remove="UnitOfWork\**" />
    <EmbeddedResource Remove="Events\**" />
    <EmbeddedResource Remove="ValueObjects\**" />
    <None Remove="UnitOfWork\**" />
    <None Remove="Events\**" />
    <None Remove="ValueObjects\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Moq" Version="4.20.69" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Services\Identity\Identity.Domain\Identity.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Entities\" />
  </ItemGroup>
</Project>
