<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MongoDB.Bson" Version="3.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emulator.Repository\Emulator.Repository.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Caching\Caching.csproj" />
  </ItemGroup>

</Project>
