// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Product.Infrastructure.Persistence;

#nullable disable

namespace Product.Domain.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251113154455_UpdateKitProductTbl")]
    partial class UpdateKitProductTbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Product.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Components", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.KitComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMainComponent")
                        .HasColumnType("boolean");

                    b.Property<int>("KitId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("KitId");

                    b.ToTable("KitComponents", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.KitImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("KitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitId");

                    b.ToTable("KitImages", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.KitProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRangeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Dimensions")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("KitProducts", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessSupportDetail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurriculumCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxStudentSeats")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTeacherSeats")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.PlanBillingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAddOn")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxStudentSeats")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTeacherSeats")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentPlanBillingCycleId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParentPlanBillingCycleId");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanBillingCycles", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.PlanCurriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("integer");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("PlanCurriculums", (string)null);
                });

            modelBuilder.Entity("Product.Domain.Entities.KitComponent", b =>
                {
                    b.HasOne("Product.Domain.Entities.Component", "Component")
                        .WithMany("KitComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product.Domain.Entities.KitProduct", "KitProduct")
                        .WithMany("KitComponents")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("KitProduct");
                });

            modelBuilder.Entity("Product.Domain.Entities.KitImage", b =>
                {
                    b.HasOne("Product.Domain.Entities.KitProduct", "Kit")
                        .WithMany("KitImages")
                        .HasForeignKey("KitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kit");
                });

            modelBuilder.Entity("Product.Domain.Entities.PlanBillingCycle", b =>
                {
                    b.HasOne("Product.Domain.Entities.PlanBillingCycle", "ParentPlanBillingCycle")
                        .WithMany("AddOnBillingCycles")
                        .HasForeignKey("ParentPlanBillingCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Product.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanBillingCycles")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentPlanBillingCycle");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Product.Domain.Entities.PlanCurriculum", b =>
                {
                    b.HasOne("Product.Domain.Entities.Plan", "Plan")
                        .WithMany("PlanCurriculums")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Product.Domain.Entities.Component", b =>
                {
                    b.Navigation("KitComponents");
                });

            modelBuilder.Entity("Product.Domain.Entities.KitProduct", b =>
                {
                    b.Navigation("KitComponents");

                    b.Navigation("KitImages");
                });

            modelBuilder.Entity("Product.Domain.Entities.Plan", b =>
                {
                    b.Navigation("PlanBillingCycles");

                    b.Navigation("PlanCurriculums");
                });

            modelBuilder.Entity("Product.Domain.Entities.PlanBillingCycle", b =>
                {
                    b.Navigation("AddOnBillingCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
